### Reload plugins
PUT http://127.0.0.1:9080/apisix/admin/plugins/reload
X-API-KEY: edd1c9f034335f136f87ad84b625c8f1pedd1c9f034335f136f87ad84b625c8f1

### Get file from OSS
GET http://127.0.0.1:9080/oss/upload/20210906/891b1ffa87f561afb3ffef190a6fd7c1.xlsx?Blade-Auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiIwMDAwMDEiLCJyZWFsX25hbWUiOiJsa3giLCJhdmF0YXIiOiIiLCJhdXRob3JpdGllcyI6WyJjZl9zYXNzIl0sImNsaWVudF9pZCI6InNhYmVyIiwicm9sZV9uYW1lIjoiY2Zfc2FzcyIsImxpY2Vuc2UiOiJwb3dlcmVkIGJ5IGJsYWRleCIsInBvc3RfaWQiOiIxMTIzNTk4ODE3NzM4Njc1MjAxIiwidXNlcl9pZCI6IjE0MzE0NjA4NDE4MjkzNTU1MjIiLCJyb2xlX2lkIjoiMTQzMTQ2MjYyMjg0MDY5MjczOCIsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiJsa3h0ZXN0Iiwib2F1dGhfaWQiOiIiLCJkZXRhaWwiOnsidHlwZSI6IndlYiJ9LCJleHAiOjE2MzEwMDA0NzQsImRlcHRfaWQiOiIxMTIzNTk4ODEzNzM4Njc1MjAxLDExMjM1OTg4MTM3Mzg2NzUyMDIiLCJqdGkiOiI1NTEwYjg2YS0zMzBmLTRlNWMtOTM2ZC0yNGFhN2IxZjc2ZWUiLCJhY2NvdW50IjoiMDAwMDAxIn0.gdbrOsZsjHdgvEK__LntLDwi6f0BMOkya4ZsRJG3Uqo
